gesdinet_jwt_refresh_token:
    ttl: 300 # 5 minutes
    ttl_update: true
    user_provider: app_user_provider
    refresh_token_entity: App\Entity\RefreshToken
    token_parameter_name: refresh_token
    entity_manager: doctrine.orm.default_entity_manager
